version: '3.4'
services:
  main_reverse_proxy:
      # Notice main_reserve_proxy/install.sh should have been executed before docker-compose!
      image: owge_main_reverse_proxy:${OWGE_CI_VERSION}
      build: main_reverse_proxy/.
      volumes:
        - ${STATIC_IMAGES_DIR}:/var/owge_data/static
        - ${DYNAMIC_IMAGES_DIR}:/var/owge_data/dynamic
      links:
        - "admin_panel_and_rest_game:owgejava_admin_and_rest_game"
      ports:
        - "${OWGE_PORT}:80"
      logging:
        driver: "json-file"
        options:
          max-size: "20m"
          max-file: "10"
  admin_panel_and_rest_game:
      image: admin_panel_and_rest_game:${OWGE_CI_VERSION}
      environment:
        - OWGE_REST_WAR_FILENAME
        - CATALINA_OPTS=-Xmx2000m -Xms100m -XX:MaxPermSize=96m
        - OWGE_DB_URL
        - OWGE_DB_USER
        - OWGE_DB_PASS
        - OWGE_CONTEXT_PATH=/game_api
      build:
          context: admin_panel_and_rest_game/.
          args:
            - warHolderDirectory=target
            - OWGE_REST_WAR_FILENAME
            - OWGE_UNIVERSE_ID
      volumes:
          - ${STATIC_IMAGES_DIR}:/var/owge_data/static
          - ${DYNAMIC_IMAGES_DIR}:/var/owge_data/dynamic
          - /public/owge-data/keys:/var/owge_data/keys
      expose:
          - "8081"
      logging:
        driver: "json-file"
        options:
          max-size: "20m"
          max-file: "10"

