##
# lib.sh is also *executed* as the main script of standalone helpers (notably
# images_creation run/build scripts); when that happens, BASH_SOURCE is
# unavailable and this file has no meaning as "the library being sourced".
##
[ -z "${BASH_SOURCE[0]-}" ] && exit 0;

kevinsuiteRoot="/public/kevinsuite-java";
kevinsuiteCommonBackend="$kevinsuiteRoot/common-backend";
kevinsuiteRestBackend="$kevinsuiteRoot/backend-rest-commons";

##
# Container runtime selection (docker | podman)
#
# OWGE scripts historically assumed the Docker CLI. Podman (>= 4, with its
# Docker-compatible API) is a drop-in alternative: same compose files, same
# `docker`-flavored commands, driven by `docker-compose` (v2) or `podman quad`
# against the podman socket.
#
#   OWGE_RUNTIME=docker|podman  force a runtime (else auto-detected)
#   PODMAN_SOCKET               override the podman socket path
#
# Sourcing this file installs a `docker` wrapper at the front of PATH (a real
# file, so pipes and `xargs docker ...` reach it): every `docker ...` call in
# the sourcing script transparently dispatches to the chosen runtime binary.
#
# @author Kevin Guanche Darias
##
function owgeRuntime () {
        if [ -n "$OWGE_RUNTIME" ]; then
                echo "$OWGE_RUNTIME";
                return;
        fi
        # NB: a real docker CLI (if any) must be found with `type -P` (binary
        # only), since the installed wrapper shadows the `docker` name on PATH.
        if commandExists podman; then
                echo "podman";
        elif type -P docker &> /dev/null; then
                echo "docker";
        fi
}

##
# Pins the container runtime, bootstraps the podman API service when needed,
# and installs the `docker` wrapper on PATH (a real binary, so pipes and
# xargs can reach it too). Idempotent; safe to call more than once.
#
# @author Kevin Guanche Darias
##
function initContainerRuntime () {
        # Resolve the runtime (auto-detect unless OWGE_RUNTIME pins it), then
        # validate it and bootstrap any runtime-specific prerequisites.
        _OWGE_RUNTIME="${_OWGE_RUNTIME-$(owgeRuntime)}";
        case "$_OWGE_RUNTIME" in
                podman)
                        commandExists podman || { log error "podman not found, install it or set OWGE_RUNTIME=docker"; return 1; };
                        podmanSocketReady || return 1;
                        ;;
                docker|"")
                        _OWGE_RUNTIME="docker";
                        export _OWGE_RUNTIME;
                        type -P docker &> /dev/null || { log error "docker runtime selected but the docker CLI is not on PATH (set OWGE_RUNTIME=podman for podman)"; return 1; };
                        ;;
                *)
                        log error "OWGE_RUNTIME must be 'docker' or 'podman' (got: $_OWGE_RUNTIME)";
                        return 1;
                        ;;
        esac
        # The wrapper binary reads OWGE_RUNTIME (its generated dispatch keys
        # off it); mirror the resolved runtime there, not just in _OWGE_RUNTIME.
        export OWGE_RUNTIME="$_OWGE_RUNTIME";
        _installRuntimeWrapper;
        export _OWGE_RUNTIME;
}

##
# Installs a real `docker` binary at the front of PATH (not a shell function,
# so pipes and `xargs docker ...` in the sourcing script reach it). It is a
# thin dispatch to the runtime `initContainerRuntime` resolved, pinned in the
# exported OWGE_RUNTIME env var. The wrapper lives in a deterministic per-user
# dir (shared across re-sources and child processes) and is rewritten in
# place.
#
# @author Kevin Guanche Darias
##
function _installRuntimeWrapper () {
        # Deterministic per-user wrapper dir: re-sources and child processes
        # share it, so /tmp doesn't accumulate a dir per process. (The file
        # is small and its content depends only on the resolved docker path,
        # so overwriting is safe.)
        _owge_runtime_dir="${XDG_RUNTIME_DIR:-/tmp}/owge_runtime_$UID";
        mkdir -p "$_owge_runtime_dir" 2> /dev/null || _owge_runtime_dir="$(mktemp -d /tmp/owge_runtime_XXXXXX)";
        # The wrapper's docker case must exec the real CLI; capture its path.
        _owge_real_docker="$(type -P docker 2> /dev/null || true)";
        cat > "${_owge_runtime_dir}/docker" <<OWGE_DOCKER_WRAPPER
#!/bin/sh
# OWGE container-runtime wrapper (generated by lib.sh initContainerRuntime).
# Forwards to the runtime pinned in OWGE_RUNTIME (podman | docker).
case "\${OWGE_RUNTIME-podman}" in
	podman) exec podman "\$@" ;;
	docker) exec "${_owge_real_docker}" "\$@" ;;
esac
OWGE_DOCKER_WRAPPER
        chmod +x "${_owge_runtime_dir}/docker";
        export PATH="${_owge_runtime_dir}:$PATH";
}

##
# Ensures the podman Docker-compatible API is serving and exports DOCKER_HOST.
# Starts `podman system service` in a detached tmux session when the socket is
# absent. Returns 1 if the service could not be brought up.
#
# @env PODMAN_SOCKET override the socket path
# @author Kevin Guanche Darias
##
function podmanSocketReady () {
        _podmanSocket="${PODMAN_SOCKET:-${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/podman/podman.sock}";
        _serving="";
        if [ -S "$_podmanSocket" ] && { ! commandExists curl || curl -s --max-time 2 --unix-socket "$_podmanSocket" http://127.0.0.1/_ping 2>/dev/null | grep -q OK; }; then
                _serving=1;
        fi
        if [ -z "$_serving" ]; then
                commandExists tmux || { log error "Podman API is not running and tmux is not available to start it. Start it yourself: podman system service --time 0"; return 1; };
                log info "Starting podman API service in tmux session 'owge-podman-svc' (socket $_podmanSocket)";
                tmux new-session -d -s owge-podman-svc "podman system service --time 0";
                _i=0;
                while [ $_i -lt 10 ]; do
                        sleep 1;
                        if [ -S "$_podmanSocket" ] && { ! commandExists curl || curl -s --max-time 2 --unix-socket "$_podmanSocket" http://127.0.0.1/_ping 2>/dev/null | grep -q OK; }; then
                                _serving=1;
                                break;
                        fi
                        _i=$((_i + 1));
                done
                if [ -z "$_serving" ]; then
                        log error "Podman API did not answer on $_podmanSocket after 10s";
                        return 1;
                fi
        fi
        export DOCKER_HOST="unix://$_podmanSocket";
}

##
# Low-priority helpers, so a build doesn't starve the running universes.
#
# The heavy compilers (mvn, ng) run INSIDE docker containers, as children of the
# docker daemon, so they don't inherit the script's nice value. We therefore split
# the problem in two:
#   - lowerHostPriority: re-execs the script under nice/ionice, covering the
#     host-side work the script does directly (cp, rm, git, docker build context).
#   - dockerBuildPriorityArgs: cgroup weights to pass to the build `docker run`s,
#     which DO throttle the in-container compilers (only bite under contention,
#     full speed when the host is idle).
#
# Linux-only (no-ops elsewhere). Tunable via OWGE_NICE_LEVEL, OWGE_IONICE_CLASS,
# OWGE_DOCKER_CPU_SHARES, OWGE_DOCKER_BLKIO_WEIGHT (set the latter empty to skip it
# on kernels/storage drivers that reject --blkio-weight).
#
# @author Kevin Guanche Darias
##
function lowerHostPriority () {
        if [ -n "$OWGE_PRIORITY_LOWERED" ] || [ "`uname -s`" != "Linux" ]; then
                return 0;
        fi
        export OWGE_PRIORITY_LOWERED=1;
        _prio="";
        commandExists nice && _prio="nice -n ${OWGE_NICE_LEVEL-19}";
        commandExists ionice && _prio="$_prio ionice -c ${OWGE_IONICE_CLASS-3}";
        if [ -n "$_prio" ]; then
                >&2 echo -e "\e[36mRunning build under low host priority ($_prio)\e[39m";
                exec $_prio "$0" "$@";
        fi
}

##
# Echoes the docker cgroup weight flags for build containers (stdout only, so it
# can be captured straight into a `docker run` line). Empty on non-Linux.
#
# @author Kevin Guanche Darias
##
function dockerBuildPriorityArgs () {
        test "`uname -s`" = "Linux" || return 0;
        # Podman run has no --cpu-shares/--blkio-weight; only the docker daemon
        # honors these cgroup weights.
        case "${_OWGE_RUNTIME-}" in
                podman) return 0 ;;
        esac
        echo -n "--cpu-shares=${OWGE_DOCKER_CPU_SHARES-256}";
        if [ -n "${OWGE_DOCKER_BLKIO_WEIGHT-100}" ]; then
                echo -n " --blkio-weight=${OWGE_DOCKER_BLKIO_WEIGHT-100}";
        fi
}

function nodeRun() {
        _targetDirectory="$1";
        if [ ! -d "$_targetDirectory" ]; then
                echo "FATAL, nodeRun failed, no such directory $_targetDirectory, aborting script execution";
                exit 1;
        fi
        shift;
        docker run -it --rm `dockerBuildPriorityArgs` --volume "$_targetDirectory"://home/node -w=/home/node docker.io/library/node:8-alpine $@
}

##
# Will check if given env-var is defined
#
# @param $1 string env var name
# @param $2 string current value of the env var
# @param $3 string Additional optional hint
# @author Kevin Guanche Darias
##
function envFailureCheck(){
	if [ -z "$2" ]; then
                _hint="";
                test -n "$3" && _hint="Hint: $3";
		>&2 echo  -ne "\e[31mError: \e[39m";
                >&2 echo "Environment is not properly configured, missing $1, $3";
		exit 1;
	fi
}

function envInfoCheck() {
        if [ -z "$2" ]; then
                _hint="";
                test -n "$3" && _hint="Hint: $3";
		echo -ne "\e[32mInfo: \e[39m";
                echo "Optional $1 not specified, $3";
		exit 1;
        fi
}

##
# Returns the HTTP port for the specified OWGE universe
#
# @param $1 int Unirverse id
# @returns stdout<int> Port number
# @author Kevin Guanche Darias
##
function getPortByUniverseId () {
	if ! [ "$1" -eq "$1" ] 2> /dev/null; then
		echo "FATAL, param passed to getPortByUniverseId is not a number, passed: $1";
		return 1;
	fi;
	_basePort=8110;
	_port=$(( $_basePort + $1 ));
	if nc -z 127.0.0.1 $_port; then
		echo "FATAL, port $_port is already in use";
		return 1;
	fi
	echo "$_port";
}

function compileAngularProject () {
        test -d "$1/dist" && rm -r "$1/dist";
        test -d "$1" && echo "Compiling Angular project in $1 to $2";
        if [ -d "$2" ]; then
                echo "FATAL, target directory for angular project alreadt exists, used $2, aborting...";
                exit 1;
        fi
        cp -rp "$1" "$2";
        nodeRun "$2" npm install &> /dev/null;
        nodeRun "$2" npm run build &> /dev/null;
        if [ ! -d "$2/dist" ]; then
                echo "FATAL, Angular compilation failed, aborting script execution";
                exit 1;
        fi

}

function gitGetCurrentBranch () {
	git branch | grep '^*' | cut -c 3-;
}

function gitVersionExists () {
	if ! echo "$1" | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$" &> /dev/null; then
                echo "FATAL, malformed version passed to gitVersionExists(), exit()ing script";
                return 1;
        fi
	major=`echo $1 | cut -d . -f 1`;
        minor=`echo $1 | cut -d . -f 2`;
        patch=`echo $1 | cut -d . -f 3`;
	if [[ $major -eq 0 && $minor -eq 3 && $patch -lt 5 ]] || [[ $major -eq 0 && $minor -eq 4 && $patch -lt 1 ]] || [[ $major -eq 0 && $minor -lt 3 ]]; then
		echo "Unsupported version v$1, only versions equal or grater than 0.3.5, 0.4.1, or, having minor equal or greater to 5 can be used";
		return 1;
	elif git tag | grep v$1 &> /dev/null; then
		return 0;
	else
		echo "NO SUCH version exists, v$1 is not a git tag";
		return 1;
	fi

}

function rollback () {
	git checkout "$oldBranch";
	exit 1;
}

function checkDirectoryExists () {
        if [ ! -d "$1" ]; then
	        echo "Directory $1 doesn't exists!";
	        exit 1;
        fi
}

##
# Exits with 1 if specified script has less arguments than expected
#
# @param $1 int Number of passed arguments (usually is $#)
# @param $2 int Number of expected arguments
# @param $3 string Additional error information
# @author Kevin Guanche Darias
##
function checkRequiredArguments () {
        if [ "$1" -lt "$2" ]; then
                echo "Err, the script requires $2 params, but specified $1. $3";
                exit 1;
        fi
}

##
# Exits with 1 if specified docker image doesn't exists
#
# @param $1 string Docker image name
# @author Kevin Guanche Darias
##
function checkDockerImageExists () {
        if [[ "$(docker images -q  "$1" 2> /dev/null)" == "" ]]; then
                echo "Image not found, must first compile it, please invoke build.sh";
                exit 1;
        fi
}

##
# Displays a deprecated log warning
#
# @param string $1 
# @author Kevin Guanche Darias
##
function deprecated () {
        if [ -n "$1" ]; then
                _useInstead=", use: $1 instead";
        fi
        log warning "$0 is deprecated";
}

##
# Prompts for a param, 
#
# @param $1 string Optional value, for use as grep expression, for example ^[0-9]{3,4}$
# @deprecated
# @author Kevin Guanche Darias
##
function promptParam () {
        deprecated $0 promptValue;
        param=
	while [ -z "$param" ]; do
		read param;
                if [ -n "$1" ] && [ -n "$param" ] && ! (echo "$param" | grep -E "$1"); then
                        echo -e "\e[31mInvalid value, retry\e[39m";
                        param="";
                fi
	done
        echo;
        echo "$param" | tr -d ' ';
}

##
# User Prompt
#
# @param $1 Display message;
# @param $2 string Optional value, for use as grep expression, for example ^[0-9]{3,4}$
# @return variable _output
# @author Kevin Guanche Darias
##
function promptValue () {
        if [ -z "$1" ]; then
                >&2 echo -e "\e[31mProgramming error.. noob programmer";
                exit 1;
        fi
        param=
	while [ -z "$param" ]; do
                echo -ne "$1: ";
		read param;
                if [ -n "$2" ] && [ -n "$param" ] && ! (echo "$param" | grep -E "$2"); then
                        echo -e "\e[31mInvalid value, retry\e[39m";
                        param="";
                fi
	done
        export _output="`echo $param`";
}

##
# Prompts for a port, if it is in use, will prompt again
#
# @param $1 string Name of the service
# @paramm $2 bool If not empty will test the Docker machine port, and not the host port (relevant for Docker Toolbox)
# @return variable _output
# @author Kevin Guanche Darias
##
function promptPort () {
        dockerFindHostIp "$2";
        _ip="$output";
        _port="";
        while [ -z "$_port" ]; do
                promptValue "Insert $1 port" "^[0-9]{2,5}$";
                if isPortOpen "$_ip" "$_output" ; then
                        echo -e "\e[31mPort $_output already in use\e[39m";
                else
                        _port="$_output";
                fi
        done
        export _output="`echo $_port`";
}

##
# Prompts once, if no response, will return the default
#
# @param $1 string Prompt message
# @param $2 string Default value
# @param $3 string (Optional) Test command, if invalid will ask again, notice "€" will be replaced by the user input value
# @param $4 string (Optional) When specified, represents a "hint" to show when the test command fails
# @return variable _output
# @author Kevin Guanche Darias
##
function promptWithDefault () {
        export _output="";
        echo -ne "$1 [\e[33m$2\e[39m]: ";
        read _value;
        while [ -z "$_output" ]; do
                if [ -n "$3" ] && [ -n "$_value" ] && ! (echo "$_value" | xargs -I€ bash -c "$3"); then
                        _command="`echo "$_value" | xargs -I€ echo "$3"`";
                        log debug "promptWithDefault test command has been specified ($_command) and input has an INVALID string";
                        >&2 echo -ne "\e[31mInvalid input \e[39m";
                        >&2 test -n "$4" && echo -ne "Hint: \e[35m$4\e[39m";
                        export _output="";
                        echo
                        echo -ne "$1 [\e[33m$2\e[39m]: ";
                        read _value;
                elif [ -z "$_value" ]; then
                        log debug "promptWithDefault empty value";
                        export _output="$2";
                else
                        log debug "promptWithDefault value defined";
                        export _output="$_value";
                fi
        done
        log debug "Returning value $_output";
}

##
# Checks if a command exists
#
# @param $1 string The command name
# @see https://github.com/thetrompf/yarn/blob/8b9c5f3c7238d63bce3b347472f3205cee01ddcf/bin/yarn#L10
##
function commandExists () {
        command -v "$1" >/dev/null 2>&1;
}

##
# Finds the absolute dir for given relative dir
# 
# @param $1 string relative dir
# @see https://stackoverflow.com/a/31605674
##
function findAbsoluteDir () {
        echo "$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
}

##
# Logs a message, if no DEBUG_LEVELS is specified, will only DEBUG errors 
#
# @param string $1 log level, for example  "debug"
# @param string $2 log message
# @param string $3 color, for example: 1 = red, 2 = green
#
# @env DEBUG_LEVELS specified levels, separated by spaces. Ex: DEBUG_LEVELS="warning error", usually valid values are debug, info, warning, error
#
# @author Kevin Guanche Darias
##
function log () {
        if [ -n "$DEBUG_LEVELS" ]; then
                _log_levels="$DEBUG_LEVELS";
        else
                _log_levels="error,warning";
        fi
        if echo "$_log_levels" | grep "$1" &> /dev/null; then
                if [ "$1" == "warning" ]; then
                        _defaultColor="3";
                elif [ "$1" == "error" ]; then
                        _defaultColor="1";
                else 
                        _defaultColor="2";
                fi
                echo -e "\e[3${3-$_defaultColor}m${1^^} [`date -Ins | cut -d + -f 1`]: $2\e[39m";
        fi
}

function  dockerNetTools() {
        docker run --rm -i amouat/network-utils $@;
}

##
# Finds the IP of the system running docker (recommended when wanting to support Docker toolbox)
#
# @param $1 bool If non-empty will return docker machine IP when running in Docker toolbox 
# @return variable output
#
# @author Kevin Guanche Darias
##
function dockerFindHostIp () {
        log info "While the default Host or IP may look \"strange\", it's the internal IP used by the container runtime";
        # The toolbox branch is for remote tcp:// DOCKER_HOSTs (docker-machine).
        # Podman exports DOCKER_HOST as a unix:// socket but is local, so it
        # must not be treated as toolbox.
        if [ -n "$DOCKER_HOST" ] && [ "${_OWGE_RUNTIME-docker}" != "podman" ]; then
                log debug "The user is using docker toolbox";
                if [ -z "$1" ]; then
                        export output=`echo $DOCKER_HOST | cut -d ':' -f 2 | cut -c 3- | sed -e 's/\.[0-9]*$/.1/g'`;
                else 
                        export output=`echo $DOCKER_HOST | cut -d ':' -f 2 | cut -c 3-`;
                        log debug "Docker-Machine IP is $output";
                fi
        else
                # Local unix socket: the host is the runtime's default bridge
                # gateway, reachable from containers. The Win/Mac docker probe
                # is skipped for podman (no host.docker.internal there, and it
                # would only cost an alpine pull).
                if [ -z "$DOCKER_HOST" ] && [ "${_OWGE_RUNTIME-docker}" != "podman" ] && docker run --rm -i alpine ping -c 2 host.docker.internal &> /dev/null; then
                        log debug "The user is using Windows 10/Mac docker";
                        export output="host.docker.internal";
                else
                        log debug "The user is using Linux native docker/podman";
                        export output="`dockerNetTools 'ip route show' | grep default | cut -d \  -f 3;`";
                fi
        fi
}

function isPortOpen () {
        dockerNetTools nmap $1 -p $2 | grep "tcp open " &> /dev/null
}

##
# Waits till an specified command returns true
#
# @param $1 string $Waiting message
# @param ...$2 string Command
#
# @env attemps Number of attemps, defaults to 5
# @env delay Delay in second, defaults to 1 
#
# @author Kevin Guanche Darias
##
function waitFor () {
        _waitingMessage="$1";
        shift;
        _attemps=${attemps-5};
        _i=0;
        log debug "Running waitFor command: $@";
        while ! bash -c "$@" &> /dev/null; do
                echo -e "$_waitingMessage";
                sleep ${delay-1};
                _i=`expr $_i + 1`;
                if [ "$_i" -eq "$_attemps" ]; then
                        bash -c "$@";
                        >&2 echo -e "\e[31mAborting due to error";
                        exit 1;
                fi
        done
}


##
# Waits till an specified command returns true
#
# @param $1 string $Waiting message
# @param ...$2 string Command
#
# @env attemps Number of attemps, defaults to 5
# @env delay Delay in second, defaults to 1 
#
# @author Kevin Guanche Darias
##
function waitForSimple () {
        _waitingMessage="$1";
        shift;
        _attemps=${attemps-5};
        _i=0;
        log debug "Running waitFor command: $@";
        while ! "$@" &> /dev/null; do
                echo -e "$_waitingMessage";
                sleep ${delay-1};
                _i=`expr $_i + 1`;
                if [ "$_i" -eq "$_attemps" ]; then
                        "$@";
                        >&2 echo -e "\e[31mAborting due to error";
                        exit 1;
                fi
        done
}


function ctrl_c() {
        log debug "** Trapped CTRL-C"
        if [ ${script_in_query-0} -eq 1 ]; then
                log warning "An outgoing mysql query is executing, please wait"
                script_aborted=1
        else
                trap INT;
                exit 1;
        fi

}

##
# Runs a MySQL command, against the known to be the mysql connection
# 
# @param string $1 the command itself If not specified, will read from stdin
# @env OWGE_DB_URL
# @env OWGE_DB_USER
# @env OWGE_DB_PASS
##
function mysql_run() {
        if [ -n "$script_aborted" ]; then
                log error "Can't run MySQL command as script is aborted";
                return 1;
        fi
	_mysql_host_and_port=`echo "$OWGE_DB_URL" | cut -d '/' -f 1`;
	_mysql_db=`echo "$OWGE_DB_URL" | cut -d '/' -f 2`;
	_mysql_host=`echo "$_mysql_host_and_port" | cut -d ':' -f 1`;
	_mysql_port=`echo "$_mysql_host_and_port" | cut -d ':' -f 2`;
        if [ -z "$1" ]; then
                _command='cat';
                _filename=/tmp/`date +%s`.tmp;
                cat > $_filename
                _concat="< $_filename";
        else
                _command="echo $1";
                _concat="";
        fi
	( 
                if [ -z  "$_concat" ]; then
                        $_command | MYSQL_PWD="$OWGE_DB_PASS" mysql -h "$_mysql_host" -P "$_mysql_port" -u "$OWGE_DB_USER" $_mysql_db;
                else
                        $_command | MYSQL_PWD="$OWGE_DB_PASS" mysql -h "$_mysql_host" -P "$_mysql_port" -u "$OWGE_DB_USER" $_mysql_db < $_filename;
                fi
        ) &
        _pid=$!;
        _count=0;
        script_in_query=1;
        while [ -d /proc/$_pid ]; do
                _count=$(($_count + 1));
                if [ $(($_count % 5 )) -eq 0 ]; then
                        log warning "The mysql query is taking long time";
                fi
                sleep 1;
        done
        wait $_pid;
        _result=$?;
        script_in_query=0;
        if [ ${script_aborted-0} -eq 1 ]; then
                log debug "Killing as wanted";
                trap INT;
                exit 1;
        fi
        return $_result;
}

##
# Pins the container runtime to docker (deploy scripts target a stable
# production runtime; the dev launcher auto-detects podman). No-op if already
# podman.
#
# @author Kevin Guanche Darias
##
function pinDockerRuntime () {
        export OWGE_RUNTIME="docker";
}

##
# Tears down a compose project with a podman fallback. `docker compose down`
# fails on rootless podman when killing the slirp4netns network process
# ("rootless netns: kill network process: permission denied"); the containers
# stop but the project's network is orphaned. This runs the plain down and,
# when it errors, finishes the job via the podman CLI (container + network
# cleanup) so a relaunch on the same profile starts clean.
#
# @param ... $@ compose invocation args, i.e. the _launchLine files plus -p <project>
# @author Kevin Guanche Darias
##
function owgeComposeDown () {
        if docker compose "$@" down --remove-orphans 2> /dev/null; then
                return 0;
        fi
        # Fall back to the podman CLI for the netns-kill bug.
        if [ "${_OWGE_RUNTIME-docker}" = "podman" ]; then
                _project_name="";
                _expect_project=0;
                for _a in "$@"; do
                        if [ "$_expect_project" = "1" ]; then
                                _project_name="$_a";
                                _expect_project=0;
                        fi
                        [ "$_a" = "-p" ] && _expect_project=1;
                done
                log warning "compose down failed; cleaning project ${_project_name-<unnamed>} via podman CLI";
                [ -n "$_project_name" ] && podman container rm -f --filter "label=com.docker.compose.project=$_project_name" 2> /dev/null;
                [ -n "$_project_name" ] && podman network rm "${_project_name}_default" 2> /dev/null;
        fi
        return 0;
}

##
# Returns with error if mysql query fails (empty result)
#
# @param string $1 The query to run
# @param string $2 extra filter
#
##
function check_mysql_query_fails() {
	_extra_filter="${2-cat}";
	test `mysql_run "$1" | $_extra_filter | wc -l` -eq 0;
}

export log_has_displayed_levels=${log_has_displayed_levels-0};
(
        if [ $log_has_displayed_levels -eq 0 ]; then
                _levels=${DEBUG_LEVELS-error};
                for level in ${_levels//,/ }; do
                        log $level "Level $level is enabled";
                done
        fi
)
export log_has_displayed_levels=1;

##
# Auto-wire the container runtime when sourced by a dev script (images_creation
# run/build helpers, the launcher, etc.) rather than executed. The dev flow
# wants podman when available; the deploy scripts stay on docker because they
# call pinDockerRuntime (which sets OWGE_RUNTIME=docker) before any docker call.
# Guarded so re-sourcing and the deploy-pin path don't fight.
#
# @author Kevin Guanche Darias
##
if [ -n "${BASH_SOURCE[0]-}" ] && [ -z "${_OWGE_RUNTIME-}" ] && [ -z "${OWGE_RUNTIME-}" ] && [ -z "$_owge_auto_init_done" ]; then
        _owge_auto_init_done=1;
        # Podman-host preference: only auto-switch to podman when no real
        # docker CLI is present, so deploy/CI machines (which have docker)
        # keep the real docker binary and the pinDockerRuntime default.
        if commandExists podman && [ -z "$(type -P docker 2> /dev/null)" ]; then
                _OWGE_RUNTIME="podman";
                export OWGE_RUNTIME="podman";
                podmanSocketReady 2> /dev/null || true;
                _installRuntimeWrapper;
        fi
        export _OWGE_RUNTIME;
fi
