/**
 * @since 0.7.4
 */
export type validConfigurationParam = 'MISSION_TIME_EXPLORE' | 'MISSION_TIME_GATHER' | 'MISSION_TIME_ATTACK' | 'MISSION_TIME_CONQUEST'
 | 'MISSION_TIME_COUNTERATTACK' | 'MISSION_TIME_DEPLOY' | 'MISSION_TIME_ESTABLISH_BASE' | 'DEPLOYMENT_CONFIG';
