# Step Compile business, rest & admin
FROM maven:3-jdk-11-openj9 as game-war-files
WORKDIR /build/business
COPY business/pom.xml .
RUN mvn dependency:go-offline
COPY business/src /build/business/src
RUN mvn install -DskipTests

WORKDIR /build/rest
COPY game-rest/pom.xml .
RUN mvn dependency:go-offline
COPY game-rest/src /build/rest/src
RUN mvn install -DskipTests

# Tomcat base
FROM tomcat:8-jdk11 as tomcat-base
COPY docker-ci/dev/images_creation/tomcat_config/* /usr/local/tomcat/conf/
COPY docker-ci/dev/images_creation/scripts/* /
RUN apt-get update && apt-get install -y default-mysql-client
CMD ["/wait_mysql.sh","catalina.sh", "run"]

# Game REST Image
FROM tomcat-base as game-rest
LABEL maintainer "Kevin Guanche Darias <kevin@kevinguanchedarias.com>"
COPY --from=game-war-files /build/rest/target/*.war /usr/local/tomcat/webapps/game_api.war

# Game REST & Game admin
FROM tomcat-base as game-rest-and-admin
LABEL maintainer "Kevin Guanche Darias <kevin@kevinguanchedarias.com>"
COPY --from=game-war-files /build/rest/target/*.war /usr/local/tomcat/webapps/game_api.war
