# Step Compile business, rest & admin
FROM maven:3-openjdk-17-slim as game-war-files
WORKDIR /build/business
COPY business/pom.xml .
RUN mvn dependency:go-offline
COPY business/src /build/business/src
RUN mvn install -DskipTests

WORKDIR /build/rest
COPY game-rest/pom.xml .
RUN mvn dependency:go-offline
COPY game-rest/src /build/rest/src
RUN mvn install -DskipTests

# Tomcat base
FROM eclipse-temurin:17-jdk-focal as spring-base
RUN apt update && apt install -y  mysql-client
RUN addgroup spring && adduser -S spring -G spring
RUN mkdir /app
RUN chown spring:spring /app
USER spring:spring
ENV OWGE_CONTEXT_PATH=/game_api
COPY docker-ci/dev/images_creation/scripts/* /
CMD ["/wait_mysql.sh","java", "-jar", "/app/game_api.jar"]
ENTRYPOINT ["/bin/sh"]

# Game REST & Game admin
FROM spring-base as game-rest-and-admin
EXPOSE 8080
EXPOSE 7474
LABEL maintainer "Kevin Guanche Darias <kevin@kevinguanchedarias.com>"
COPY --from=game-war-files /build/rest/target/*.jar /app/game_api.jar

