package com.kevinguanchedarias.owgejava.enumerations;

public enum AuditActionEnum {
    SUBSCRIBE_TO_WORLD, LOGIN, REGISTER_MISSION, ADD_PLANET_TO_LIST, BROWSE_COORDINATES,
    USER_INTERACTION, ATTACK_INTERACTION, JOIN_ALLIANCE, ACCEPT_JOIN_ALLIANCE
}
